export enum ActionTypeComplaint {
    GET_ALL_COMPLAINT_SUCCESS = "GET_ALL_COMPLAINT_SUCCESS",
    GET_ALL_COMPLAINT_FAIL = "GET_ALL_COMPLAINT_FAIL",
    REGISTER_COMPLAINT_SUCCESS = "REGISTER_COMPLAINT_SUCCESS",
    REGISTER_COMPLAINT_FAIL = "REGISTER_COMPLAINT_FAIL",
    REGISTER_COMPLAINT_LOADING = "REGISTER_COMPLAINT_LOADING",
    GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS',
    GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL',
    UPDATE_COMPLAINT_STATUS_SUCCESS = "UPDATE_COMPLAINT_STATUS_SUCCESS",
    UPDATE_COMPLAINT_STATUS_FAIL = "UPDATE_COMPLAINT_STATUS_FAIL"
}

export enum ActionTypeLogin {
    LOGGIN_SUCCESS = 'LOGGIN_SUCCESS',
    LOGGIN_FAIL = 'LOGGIN_FAIL',
    LOGGIN_LOADING = 'LOGGIN_LOADING ',
    LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
    LOGOUT_FAIL = 'LOGOUT_FAIL',
    LOGGON_SUCCESS = 'LOGGON_SUCCESS',
    LOGGON_FAIL = 'LOGGON_FAIL',
    LOGGON_LOADING = 'LOGGON_LOADING ',
}

export enum ActionTypeOfficer {
    GET_PIRAGUEROS_SUCCESS = "GET_PIRAGUEROS_SUCCESS",
    GET_PIRAGUEROS_FAIL = "GET_PIRAGUEROS_FAIL",
    GET_PIRAGUEROS_LOADING = "GET_PIRAGUEROS_LOADING",
    UPDATE_PIRAGUERO_SUCCESS = "UPDATE_PIRAGUERO_SUCCESS",
    UPDATE_PIRAGUERO_FAIL = "UPDATE_PIRAGUERO_FAIL",
    REGISTER_TRACKING_SUCCESS ="REGISTER_TRACKING_SUCCESS",
    REGISTER_TRACKING_FAIL = "REGISTER_TRACKING_FAIL",
}