export enum ActionTypeComplaint {
    GET_ALL_COMPLAINT_SUCCESS = "GET_ALL_COMPLAINT_SUCCESS",
    GET_ALL_COMPLAINT_FAIL = "GET_ALL_COMPLAINT_FAIL",
    REGISTER_COMPLAINT_SUCCESS = "REGISTER_COMPLAINT_SUCCESS",
    REGISTER_COMPLAINT_FAIL = "REGISTER_COMPLAINT_FAIL",
    REGISTER_COMPLAINT_LOADING = "REGISTER_COMPLAINT_LOADING",
    GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS',
    GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL'
}

export enum ActionTypeLogin {
    LOGGIN_SUCCESS = 'LOGGIN_SUCCESS',
    LOGGIN_FAIL = 'LOGGIN_FAIL',
    LOGGIN_LOADING = 'LOGGIN_LOADING ',
    LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
    LOGOUT_FAIL = 'LOGOUT_FAIL',
    LOGGON_SUCCESS = 'LOGGON_SUCCESS',
    LOGGON_FAIL = 'LOGGON_FAIL',
    LOGGON_LOADING = 'LOGGON_LOADING ',
}
